name: integration-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15.0]
        environment: [build]
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: Lint solution
        run: npm run lint

      - name: Build solution
        run: npm run build

      - name: Create keys
        run: echo $KEYS_JSON >> keys.json
        env:
          KEYS_JSON: ${{secrets.KEYS_JSON}}

      - name: Start ganache and test integration
        run: npm run test-ci
        env:
          CI: true

      - name: Clean keys
        run: rm -f keys.json
